# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(verbose_name='Phân quyền'),
        ),
    ]
